spring:
  application:
    name: config-demo
  config:
    import:
      - optional:configserver:http://localhost:8888
  profiles:
    active:
      - prod

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
build:
  id: ${ID}
  version: ${VERSION}
  name: ${NAME}
  type: "Default Build"