spring:
  application:
    name: config-server
  profiles:
    active:
      - native
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VIRTUAL_HOST:/}
    connection-timeout: 15000
    ssl:
      enabled: true
      verify-hostname: true
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888
