spring:
  data:
    mongodb:
      uri: ${DB_URL}
      database: ${DB_NAME}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VIRTUAL_HOST:/}
    connection-timeout: 15000
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7