spring:
  data:
    mongodb:
      uri: ${DB_URL}
      database: ${DB_NAME}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka